version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker run \
          -e POSTGRES_HOST_AUTH_METHOD=trust -d -p 5432:5432 postgres:12.2
      - run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && \
          chmod +x ./cc-test-reporter && \
          ./cc-test-reporter before-build
      - run: docker build . --file Dockerfile --tag evrone_opensource:$CIRCLE_SHA1
      - run: docker run evrone_opensource:$CIRCLE_SHA1 rubocop --parallel
      - run: |
          docker run \
          -e RAILS_DB_HOST=172.17.0.1 \
          -v ${PWD}/coverage:/srv/app/coverage \
          evrone_opensource:$CIRCLE_SHA1 \
          sh -c "rails db:setup && rails test"
      - run: ./cc-test-reporter --prefix /srv/app after-build


