name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.2
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Prepare test reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && \
        chmod +x ./cc-test-reporter && \
        ./cc-test-reporter before-build
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag evrone_opensource:$GITHUB_SHA
    - name: Run linters
      run: docker run evrone_opensource:$GITHUB_SHA rubocop --parallel
    - name: Run tests
      run: |
        docker run \
          -e RAILS_DB_HOST=172.17.0.1 \
          -v ${PWD}/coverage:/srv/app/coverage \
          evrone_opensource:$GITHUB_SHA \
          sh -c "rails db:setup && rails test"
    - name: Report coverage to CodeClimate
      run: ./cc-test-reporter --prefix /srv/app after-build
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
